# site configuration
site_name: Peach101

# theme configuration
theme:
  name: material
  language: zh

# extention configuration
markdown_extensions:
  - admonition # message block
  - pymdownx.details # as above
  - pymdownx.superfences # as above

# content
nav:
  - Peach简介: index.md
  - Peach实战: test.md